### ISSUE TITLE
CSS for content after demo blocks could do with a bit of love

### ISSUE THREAD

**Issue by bobbingwide** [zgordon/gutenberg-course#11]
I've a feeling that the CSS z-index for the content displayed with each demo block is probably a bit too high. It makes the blue text sit over the top of things. 
![image](https://user-images.githubusercontent.com/2474435/35196988-70f821c0-fed1-11e7-8834-4d59e6f8460c.png)

**Comment by zgordon** [comment]
Thanks for spotting this!  Will fix in the next update!!!

**Comment by zgordon** [comment]
This should hopefully be resolved with V2 updates :)
