### ISSUE TITLE
eslintrc file missing in starter pack

### ISSUE THREAD

**Issue by sharazghouri** [zgordon/gutenberg-course#3]
![image](https://user-images.githubusercontent.com/17900945/34709323-9f87b156-f538-11e7-9e2a-13ecdd4c6fa1.png)
![image](https://user-images.githubusercontent.com/17900945/34709387-dca842a8-f538-11e7-9721-e58f71b8a729.png)

**Comment by zgordon** [comment]
I decided not to get into including any linting files in the demo.

**Comment by zgordon** [comment]
I decided not to get into including any linting files in the demo.
