### ISSUE TITLE
withAPIData has been deprecated

### ISSUE THREAD

**Issue by mahdiyazdani** [zgordon/gutenberg-course#31]
It seems `wp.components.withAPIData` is deprecated and will be removed from Gutenberg in 3.7.

Could you update this example to use the Core Data Module or `wp.apiFetch` directly instead?

https://github.com/zgordon/gutenberg-course/blob/8f3daae2ec108f07bc7f69bbd3d61ca1144bb57a/blocks/12-dynamic/index.js#L24

**Comment by zgordon** [comment]
Resolved 👍

**Comment by zgordon** [comment]
Resolved 👍
