### ISSUE TITLE
Sass files don't get compiled in dev watch mode

### ISSUE THREAD

**Issue by fabiankaegy** [zgordon/gutenberg-course#8]
@zgordon is compiling of the sass files supposed to only happen when running the npm run build command?

**Comment by zgordon** [comment]
Nope, running dev mode should update both JS and CSS. Working for me..

Did you notice something specific was wrong? Does it would when you rub build?

**Comment by zgordon** [comment]
Take a look if this merger helped your issue https://github.com/zgordon/gutenberg-course/pull/4

**Comment by fabiankaegy** [comment]
Okay I just pulled the last update with the change from issue #4 and now it's working  👍
